name = "shortlink-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "shortlink-db"
database_id = "ae77ccfd-070e-4038-a6a2-d2fd23586319"

# CORS settings
[env.production.vars]
ALLOWED_ORIGINS = "https://link.dwx.my.id,https://shortlink-app.vercel.app,https://shortlink-app-bangundwir.vercel.app"
ADMIN_PASSWORD = "Arema123"

[env.development.vars]
ALLOWED_ORIGINS = "http://localhost:3000,https://link.dwx.my.id"
ADMIN_PASSWORD = "Arema123"
